// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface LineChart1Data {
  name:   string;
  series: Series[];
}

export interface Series {
  name:  number;
  value: number;
}
